### ISSUE TITLE
Configuration for specific filetype

### ISSUE THREAD

**Issue by Shatur** [windwp/nvim-projectconfig#1]
Usually projects have specific configuration for different filetypes. In Vim, you can create files for the appropriate file type to override settings. I would suggest to add a similar approach for this plugin.

We could allow to create a folder instead of a file for the project additionaly. In this case, inside will be `init.lua` with general settings and a number of files with appropriate names for each type. The approach is similar to how modules in lua works.

**Comment by windwp** [comment]
is that necessary?  you can do that with a simple autocmd for filetype

**Comment by Shatur** [comment]
But when I switch to another project, I would like to revert to default settings.

**Comment by Shatur** [comment]
Is it possible to define some autocmd for it?

**Comment by windwp** [comment]
you can define an augroup for autocmd when switch to another project just remove the group or override it

**Comment by Shatur** [comment]
Okay, thanks!
